Issue 108/flink connector docs
swimos/swimos-docs pull request #115
Opened 2023-10-06 08:55 UTC by PiggottDev

Cloeses #108

2023-10-06 15:42 UTC, afolson approved these changes

2023-10-09 00:58 UTC, ajay-gov requested changes
Content looks good but feels like this should be under the How-To-Guides section and not under the Reference section. Any thoughts?

2023-10-09 07:40 UTC, PiggottDev commented
I agree looking at Diataxis again, moved.

2023-10-09 12:47 UTC, afolson commented
Stuff like this can go either way imo. It can be a reference for setting up a connector or an explainer/how-to for how to set it up. Approved!

2023-10-09 12:47 UTC, afolson approved these changes

2023-10-10 06:40 UTC, ajay-gov approved these changes

2023-10-10 06:41 UTC, merged