Create monitor.md
swimos/swimos-docs pull request #139
Opened 2023-11-10 21:05 UTC by StreamingDataApps

process monitor tutorial re-write
https://github.com/swimos/swimos-docs/issues/63

2023-11-14 13:59 UTC, SirCipher requested changes

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +The Monitoring Client relies on the OSHI java library to extract system information from each host machine in the cluster. OSHI is a free JNA-based (native) Operating system and Hardware Information
Could you add a link to the OSHI repository?

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +The Monitoring Client relies on the OSHI java library to extract system information from each host machine in the cluster. OSHI is a free JNA-based (native) Operating system and Hardware Information
`swim.client.ClientRuntime`

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +;
Formatting

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +  private Value getUsage(final long timestamp) {
This timestamp is never used both here and in the code repository

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +In <a href="https://github.com/swimos/tutorial-monitor/blob/main/server/src/main/java/swim/monitor/client/SwimMonitorClient.java">`SwimMonitorClient`</a>, we will instantiate the SwimOS client runtim
"... which then starts the process monitor to feed data to the server"

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +
Empty line

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +          .didSet((nv, ov) -> {
For the tutorial and code repository, these parameters should be 'newValue' and 'oldValue' so it's immediately obvious what they are

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +By registering, the `ClusterAgent` will be able to observe when monitoring data changes for all hosts that register.
I think that this line could be a bit clearer

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +Let's look how memory usage information is computed at the machine level based on monitoring input.
I think that these next two blocks should be switched around so the guide follows the flow of the data. I.e, "When the "addUsage" lane receives a new value, it invokes `computeStatusFromUsage`"

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +The <a href="https://github.com/swimos/tutorial-monitor/blob/main/server/src/main/java/swim/monitor/agent/ClusterAgent.java">`ClusterAgent`</a> receives monitoring data for all machines that register
I'd add a link to the downlinks tutorial here

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +      machineCount++;
This isn't needed as it's the length of the machines set

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +    final ProcessMonitor processMonitor = new ProcessMonitor(swimClient, HOST_URI, systemInfo);
In the code repository, the `HOST_URI` is read from the args or defaults to 9001. But the server doesn't do the same as it just reads the recon file

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +A more complete of this source code exists as the swim-monitor demo can be found <a href="https://github.com/nstreamio/swim-monitor">here</a>.
Should this not be https://github.com/swimos/tutorial-monitor ?

2023-11-14 13:59 UTC, SirCipher commented on src/_tutorials/monitor.md
> +Now, under the `/ui` folder under project root, open `index.html` as a local file in your web browser to see results from monitoring your locate machine populate a chart.
The server could serve the UI using the `UIRouter` kernel and then the user could just open the corresponding link

2023-11-21 19:21 UTC, StreamingDataApps commented
I've addressed the previous review comments. This PR is a bit cluttered, maybe I should open a new one?

2023-11-22 12:08 UTC, SirCipher approved these changes

2023-11-28 11:08 UTC, merged