Create 2024-02-05-munin.md
swimos/swimos-docs pull request #157
Opened 2024-02-05 18:54 UTC by StreamingDataApps

Blog: Reddit bot overview #151 - initial commit

2024-02-06 15:40 UTC, SirCipher requested changes

2024-02-06 15:40 UTC, SirCipher commented on src/_posts/2024-02-05-munin.md
> +This blog post will explore the use of HTTP lanes in <a target="_blank" href="https://github.com/swimos/munin">**munin**</a>, a streaming data application built on SwimOS. **munin** is a real-time ap
I'd link to HTTP lanes here too

2024-02-06 15:40 UTC, SirCipher commented on src/_posts/2024-02-05-munin.md
> +This blog post will explore the use of HTTP lanes in <a target="_blank" href="https://github.com/swimos/munin">**munin**</a>, a streaming data application built on SwimOS. **munin** is a real-time ap
As well as the subreddit itself

2024-02-06 15:40 UTC, SirCipher commented on src/_posts/2024-02-05-munin.md
> +A design goal of **munin** is to provide a clean separation of concerns and make it easy to support a different subreddit. You'll see that the concrete Web Agents in `swim.munin.filethesebirds.swim`
These package names are incorrect. They should be `filethesebirds.*`

2024-02-06 15:40 UTC, SirCipher commented on src/_posts/2024-02-05-munin.md
> +   - unansweredApiDoRespond calls a method in SubmissionsAgentLogic to retrieve the current state of unanswered submissions.
```suggestion
   - `unansweredApiDoRespond` calls a method in SubmissionsAgentLogic to retrieve the current state of unanswered submissions.
```

2024-02-06 15:40 UTC, SirCipher commented on src/_posts/2024-02-05-munin.md
> +`SubmissionsAgent` is passed in so that its `unanswered` lane can be accessed using `keySet()` which is exposed by all MapLanes.
This section could do with explaining _what_ exactly is going on at a functionality level

2024-02-06 15:40 UTC, SirCipher commented on src/_posts/2024-02-05-munin.md
> +- Dynamic Web Agent state management for cleanup and maintenance.
I'd link to some lines in the munin repo here so people can have a look at these features; I'd link to a specific commit just in case the repo changes.

2024-02-06 16:39 UTC, StreamingDataApps commented on src/_posts/2024-02-05-munin.md
> +This blog post will explore the use of HTTP lanes in <a target="_blank" href="https://github.com/swimos/munin">**munin**</a>, a streaming data application built on SwimOS. **munin** is a real-time ap
done: https://github.com/swimos/swimos-docs/commit/a855a60b11c31ee6b2f34db71063585442ece1dc

2024-02-06 16:58 UTC, StreamingDataApps commented on src/_posts/2024-02-05-munin.md
> +`SubmissionsAgent` is passed in so that its `unanswered` lane can be accessed using `keySet()` which is exposed by all MapLanes.
Thanks, applied the changes here: https://github.com/swimos/swimos-docs/commit/db6f3677db5b208dab63037802b71dd343fbe36d

2024-02-13 21:34 UTC, brohitbrose reviewed
Looks great to me, I think you highlighted the important aspects well without getting too carried away with the additional complicated parts. Linking to code snippets in the "Next Steps" would be a powerful indeed as Tom mentioned, but I suppose the prerequisite to that is getting the new code layout merged in.

2024-02-20 16:42 UTC, StreamingDataApps commented on src/_posts/2024-02-05-munin.md
> +This blog post will explore the use of HTTP lanes in <a target="_blank" href="https://github.com/swimos/munin">**munin**</a>, a streaming data application built on SwimOS. **munin** is a real-time ap
Note, the change is implemented in a commit:
This blog post will explore the use of <a target="_blank" href="https://github.com/swimos/swimos-docs/blob/main/src/_backend/http-lanes.md">HTTP lanes</a> in <a target="_blank" href="https://github.com/swimos/munin">**munin**</a>, a streaming data application built on SwimOS. **munin** is a real-time application that assigns answers to every submission on <a target="_blank" href="https://www.reddit.com/r/whatsthisbird/">r/WhatsThisBird</a> based on comments. It analyzes most comments internally but also makes external API calls (to eBird.org) for some. The application pushes every derived answer to a PostgreSQL database and interacts with Reddit by posting comments on submissions to display the ongoing analysis.

2024-02-20 16:44 UTC, StreamingDataApps commented on src/_posts/2024-02-05-munin.md
> +- Dynamic Web Agent state management for cleanup and maintenance.
This change has already been included as well:
You can find the repo here: <a target="_blank" href="https://github.com/swimos/munin">https://github.com/swimos/munin</a>.

2024-02-20 16:51 UTC, ajay-gov commented
> > Looks good to me, @StreamingDataApps can you look at the changes suggested by @StreamingDataApps? We can then merge it. Thanks
> 
> @SirCipher @brohitbrose All changes have been included, except those that depend on the project re-factor.

@StreamingDataApps, I think @SirCipher's comments are about adding references to the code (commits) for the items specified in the "Parting Thoughts" section

2024-02-27 22:15 UTC, afolson commented
@StreamingDataApps Is this good to go now? It might be worth updating the file name to the current date before release but it's no big deal if not.

2024-02-27 22:40 UTC, ajay-gov commented
Needs one final review before we merge this one, will get to it this week

2024-02-28 01:07 UTC, ajay-gov commented
Looks good to me, @SirCipher can you take a quick look and approve?

2024-03-04 10:01 UTC, SirCipher approved these changes

2024-03-04 10:01 UTC, merged