Frontend / WARP Client documentation
swimos/swimos-docs pull request #160
Opened 2024-02-27 08:09 UTC by cwjames19

Closes #159

2024-02-27 15:12 UTC, afolson commented on src/_frontend/downlinks.md
> +_This documentation describes Swim JS packages v4.0.0-dev-20230923 or later. Users of earlier package versions may experience differences in behavior._
We have callouts if you want to use those: https://www.swimos.org/meta/styles.html#callouts--alerts

2024-03-04 10:48 UTC, SirCipher requested changes
Looks great, @cwjames19. Just a few nits here and there

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/downlinks.md
> +Downlinks come in several flavors, depending on the WARP subprotocol to which they conform. A [**ValueDownlink**]({% link _frontend/valueDownlink.md %}) synchronizes a structured value with a remote
To me, saying "...a structured value with a remote value lane" implies that only a structural/record type may be used with a value lane. It might be clearer to drop "structured" here

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/downlinks.md
> +    syncs: false, // will not sychronize with remote lane state when opened; updates only
Side note, these are normally called "keepLinked" and "keepSynced" like in the Java source. They should probably be renamed at some point

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/downlinks.md
> +<!-- A downlink may also be configured with a relative priority (`prio`), a max rate in milliseconds at which to accept updates (`rate`), and an optional body structure that can contain query or othe
Rogue comment. Is this to be updated later?

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/downlinks.md
> +Closing a downlink does not necessarily close the underlying WARP link. The WARP client will keep a link open so long as at least one downlink to a given node and lane URI remains open. This prevents
```suggestion
Closing a downlink does not necessarily close the underlying WARP link. The WARP client will keep a link open so long as at least one downlink to a given node and lane URI remains open. This prevents application components from stepping on each other's toes when they link to the same lanes of the same Web Agents. This can happen, for example, when a UI has a summary view and a detail view both display information derived from the same remote lane. The WARP link should not be closed when a detail view is hidden, if state updates are still required by the summary view. Events should also not be sent twice: once for the summary view, and once for the detail view. Neither the summary view nor the detail view should have to know about each other. And no global event dispatcher should be required, which could introduce consistency problems. WARP clients efficiently, and transparently, handle all of these cases on behalf of all downlinks.
```

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/downlinks.md
> +The `synced` method returns true if the WARP link is currently synchronized with the state of the remote lane. Users may observe synchronization using the `willSync` and `didSync` methods.
Maybe add a comment that "willX" observers are preemptive?

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/downlinks.md
> +And finally, all downlinks support registering `onEvent` and `onCommand` callbacks. The `onCommand` method accepts a callback used for observing outgoing command messages. The `onEvent` method regist
Some examples of the callbacks would be good

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/form.md
> +Here is an example of a custom Form which defines how the conversion of an entity representing a stock might look. Custom Forms should extend `Form`, which can be imported from `@swim/structure`. Thi
```suggestion
Here is an example of a custom Form which defines how the conversion of an entity representing how a stock might look. Custom Forms should extend `Form`, which can be imported from `@swim/structure`. This library should automatically be present in your bundle as a dependency of `@swim/client`.
```

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/gettingStarted.md
> +<!-- ### CommonJS/Node.js
Rogue comment

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/gettingStarted.md
> +<!-- ## Features -->
Rogue comment

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/structures.md
> +Every `Item` is either a Field or a Value. Every Field is either an Attr or a Slot. And every Value is either a Record, Data, Text, Num, Bool, Extant, or Absent. Think of Item as analogous to the set
Backtick type names here. I.e, `Field`

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/structures.md
> +Every `Item` is either a Field or a Value. Every Field is either an Attr or a Slot. And every Value is either a Record, Data, Text, Num, Bool, Extant, or Absent. Think of Item as analogous to the set
There's a bunch more below that should also be backticked

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/structures.md
> +A `Record` is a simple container of Item members, and is the only composite structure type. A Record containing only Field members is analogous to a JSON object—though unlike JSON, its keys are not r
```suggestion
A `Record` is a simple container of Item members, and is the only composite structure type. A Record containing only Field members is analogous to a JSON object — though, unlike JSON, its keys are not restricted to strings. A Record containing only Value members is similar to a JSON array. A Record with a leading Attr bears resemblance to an XML element. And a Record with a mixture of Field and Value members acts like a partially keyed list.
```

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/structures.md
> +<span id="isDefined">`isDefined(): boolean;`</span>
For all of below, do you not think it would render better if the underscores were replaced with backticks?

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/structures.md
> +<span id="target">`readonly target: Value;`</span>
Though a pain, I think some of the more complicated examples below could do with examples

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/structures.md
> +<span id="target">`readonly target: Value;`</span>
Alternatively, for the sake of getting this PR through, it could be noted in an issue for later

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/valueDownlink.md
> +description: "A WARP connection which synchronizes a shares real-time, scalar value with a remote value lane"
```suggestion
description: "A WARP connection which synchronizes a shared real-time, scalar value with a remote value lane"
```

2024-03-04 10:48 UTC, SirCipher commented on src/_frontend/whatIsWarp.md
> +## WARP
```suggestion
## WARP (Web Agent Remote Protocol)

```

2024-03-04 21:22 UTC, cwjames19 commented on src/_frontend/downlinks.md
> +Downlinks come in several flavors, depending on the WARP subprotocol to which they conform. A [**ValueDownlink**]({% link _frontend/valueDownlink.md %}) synchronizes a structured value with a remote
💯

2024-03-04 21:26 UTC, cwjames19 commented on src/_frontend/downlinks.md
> +    syncs: false, // will not sychronize with remote lane state when opened; updates only
I believe they were also called "keepLinked" and "keepSynced" in the JS source some time ago as well. Auto-gen'd docs for SwimJS v3.9(?) had it this way. I'm not sure why the change was made but I agree it'd be nice to have them matching. I'm not in love with the current JS naming convention so I'll open an issue for changing it on that end.

2024-03-04 21:26 UTC, cwjames19 commented on src/_frontend/downlinks.md
> +<!-- A downlink may also be configured with a relative priority (`prio`), a max rate in milliseconds at which to accept updates (`rate`), and an optional body structure that can contain query or othe
Nope, will remove.

2024-03-04 21:37 UTC, cwjames19 commented on src/_frontend/structures.md
> +<span id="isDefined">`isDefined(): boolean;`</span>
I thought it was more readable this way but what you suggested makes for consistency. Increasing the function signature helped.

2024-03-04 22:03 UTC, cwjames19 commented on src/_frontend/downlinks.md
> +    syncs: false, // will not sychronize with remote lane state when opened; updates only
https://github.com/swimos/swim/issues/157

2024-03-06 02:04 UTC, cwjames19 commented on src/_frontend/structures.md
> +<span id="target">`readonly target: Value;`</span>
https://github.com/swimos/swimos-docs/issues/162

2024-03-06 13:22 UTC, SirCipher approved these changes

2024-03-09 01:42 UTC, ajay-gov requested changes
Looks great!! Just a few changes and mostly suggestions otherwise

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/warpClient.md
> +`WarpClient` includes four methods that open different kinds of downlinks. The `downlink` method creates an EventDownlink for streaming raw events from any Web Agent lane. The `valueDownlink` method
`mapDownlink` is used to synchronize state with any lane in a WebAgent which is backed by a map. Hence it should be used for map lanes, join value lanes and join map lanes since the latter two are supported by maps. Not sure how you want to phrase this but this will be good to mention here and in the mapDownlinks section

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/mapDownlink.md
> +A MapDownlink synchronizes a shared real-time key-value map with a remote [**map lane**]({% link _backend/map-lanes.md %}). MapDownlinks are also the downlink best suited for use with [**join value l
As mentioned in the earlier comment, it will be good to mention join map lanes here as well

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/valueDownlink.md
> +A ValueDownlink synchronizes a shared real-time value with a remote value lane. In addition to the standard Downlink callbacks, ValueDownlink supports registering `willSet` and `didSet` callbacks to
the `willSet` stuff is a bit tricky. It will definitely get called when a client call `set` on a lane but a remote WebAgent might not necessary trigger a `willSet`. I feel like we should just refer to the `didSet` callbacks and not get into the intricacies of the `willSet` since it is confusing. Any thoughts?  Maybe for an Advanced section at some point.

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/mapDownlink.md
> +A MapDownlink synchronizes a shared real-time key-value map with a remote [**map lane**]({% link _backend/map-lanes.md %}). MapDownlinks are also the downlink best suited for use with [**join value l
The `willUpdate` and `willRemove` callbacks are tricky and non-intuitive (similar to the `willSet` callback in the `ValueLane`). My suggestion is to not mention it for now.

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/mapDownlink.md
> +A MapDownlink synchronizes a shared real-time key-value map with a remote [**map lane**]({% link _backend/map-lanes.md %}). MapDownlinks are also the downlink best suited for use with [**join value l
Should we mention that when `didUpdate` and `didRemove` callbacks are invoked, i.e when a map is updated either with a new key or an existing key for `didUpdate` and when the key in a map is removed when for `didRemove`

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/mapDownlink.md
> +A MapDownlink views its keys and values as [**Values**]({% link _frontend/structures.md %}) by default. Use the `keyForm` and `valueForm` methods to create a typed projection of a MapDownlink that au
"The `Form` class comes with a number of ready-to-use instances for basic use cases. For example, you can use `Form.forBoolean()` to coerce a ValueDownlink's state to a boolean; and you can also use `Form.forAny()` to create a ValueDownlink that coerces its state to a plain old JavaScript value."

The `ValueDownlink` here needs to be `MapDownlink` right? Will be good to mention that the `keyForm` to coerce the `key` and `valueForm` to coerce the `value` associated with that `key` in the map

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/listDownlink.md
> +---
We don't really document the `ListLane` in the backend primarily because it's a bit tricky especially when stuff moves around in the list and also because we don't really use it much. Can we hide this section for now to avoid confusion. You can keep the file and we can uncomment  it in the index once we document it in the backend?

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/eventDownlink.md
> +Using the `onEvent` callback, an application may update UI views and other dependent components in response to any messages received from the Web Agent.
Should we show examples of the `event` that would be received when the `EventDownlink` is created on a `ValueLane` and a `MapLane`, i.e the full recon message like `@update(...)`?

2024-03-09 01:42 UTC, ajay-gov commented on src/_frontend/structures.md
> +---
Everything looks good here. Was wondering if we can add a couple of examples. So take a couple of recon structures with sample data and show how to extract data from these striuctures, iterate it over etc. (based on your experience with apps there maybe just a few API calls that you use which should cover 95% of the scenarios is what I think, so maybe just document that with examples?)

2024-03-09 23:52 UTC, ajay-gov commented on src/_frontend/downlinks.md
> +
Somewhere in this section we need to mention that if a downlink is created to a node or a lane that doesn't exist then an @unlinked message will be sent with a `@nodeNotFound` or a `@laneNotFound` error  respectively. Eg:
`@unlinked(node:"/a/b",lane:l1)@nodeNotFound` or `@unlinked(node:"/a/b",lane:l1)@laneNotFound`

2024-03-12 16:47 UTC, cwjames19 commented on src/_frontend/valueDownlink.md
> +A ValueDownlink synchronizes a shared real-time value with a remote value lane. In addition to the standard Downlink callbacks, ValueDownlink supports registering `willSet` and `didSet` callbacks to
Thanks for pointing this out. I didn't know that `willSet`'s behavior was so peculiar. Will remove for now.

2024-03-14 00:13 UTC, ajay-gov approved these changes
excellent, looks great.

2024-03-14 00:17 UTC, merged