Rust release blog post
swimos/swimos-docs pull request #239
Opened 2024-07-12 15:29 UTC by SirCipher

2024-07-13 00:30 UTC, brohitbrose commented on src/_posts/2024-07-12-swimos-beta-release.md
> +Perhaps counterintuitively, many of the advantages of using SwimOS come from what it _does not_ do rather than what it _does_. SwimOS does not provides guarantees that every agent and lane within a s
I'd do a slight rephrase here. My reading of the first three sentences led me to draw false conclusions (that are cleared up by the succeeding numbered list). Maybe something like:

```
Perhaps counterintuitively, many of the advantages of using SwimOS come from what it _does not_ do rather than what it _does_.
The consistency guarantees of live data in a Swim server are strong _within_ Web Agents but weaker _across_ them.
This optimization provides for business logic that requires strong guarantees while dramatically bounding memory usage.

More specifically:
```

2024-07-14 03:58 UTC, ajay-gov requested changes
The overall content is really good. We need to make a decision on the generic SwimOS part.

2024-07-14 03:58 UTC, ajay-gov commented on src/_posts/2024-07-12-swimos-beta-release.md
> +## What is Real-Time Stream Processing?
I think this section and the next two (until Why SwimOS on Rust) are quite nice but i feel like this blog is about SwimOS on Rust. These sections are super generic and should probably be in an intro to SwimOS section which is independent of language. In this blog we should state that we assume that the reader knows enough about SwimOS already and we should point them to material in the docs website as a reference for them to read if they are not familiar with SwimOS

2024-07-14 03:58 UTC, ajay-gov commented on src/_posts/2024-07-12-swimos-beta-release.md
> +Perhaps counterintuitively, many of the advantages of using SwimOS come from what it _does not_ do rather than what it _does_. SwimOS does not provides guarantees that every agent and lane within a s
This does require a lttle bit of rephrasing. Also see comment above regarding whether this needs to be part of this blog at all.

2024-07-14 03:58 UTC, ajay-gov commented on src/_posts/2024-07-12-swimos-beta-release.md
> +Porting SwimOS to Rust provides several key benefits, as compared to the running in the JVM:
Do we need to mention JVM herer, can it be generic i.e "Porting SwimOS to Rust provides several key benefits". One of the line items can mention the comparison to Java. The points related to "Deterministic Memory Management" and "Performance" can also stand on their own without having to refer to Java

2024-07-14 03:58 UTC, ajay-gov commented on src/_posts/2024-07-12-swimos-beta-release.md
> +4. Rust Ecosystem: SwimOS on Rust is implemented using the [Tokio asynchronous runtime](https://tokio.rs/) and numerous other high quality Rust libraries making maintenance of the SwimOS code-base mu
Can we mention future language bindings here for ployglot support as one of the main motivations?

2024-07-15 14:16 UTC, horned-sphere commented on src/_posts/2024-07-12-swimos-beta-release.md
> +## What is Real-Time Stream Processing?
Tom seemed to be angling for this to be there to back up an announcement (that would be posted publically). Most people will never have heard of Swim so I was trying to make the post self contained so people didn't have to go elsewhere to find out what it is all about. I agree that, when posted on our own blog, it looks a bit strange doing the introduction here.

Unfortunately, if you restrict the content to talking about the Rust aspect, there isn't really that much to say.

2024-07-17 15:58 UTC, horned-sphere commented on src/_posts/2024-07-12-swimos-beta-release.md
> +Perhaps counterintuitively, many of the advantages of using SwimOS come from what it _does not_ do rather than what it _does_. The consistency guarantees of live data in a Swim server are strong _wit
I prefer my original phrasing, of course :). This is fine though.

2024-07-17 15:58 UTC, horned-sphere commented on src/_posts/2024-07-12-swimos-beta-release.md
> +SwimOS was previously written in Java and by switching to Rust, we achieved the following:
Saying "previously" makes it sounds like the Java version no longer exists.

2024-07-17 15:58 UTC, horned-sphere commented on src/_posts/2024-07-12-swimos-beta-release.md
> -1. No JVM Required: A typical SwimOS Rust application compiles to a small executable with no additional dependencies.
I still think it's worth highlighting that no external runtime is required (even if we don't mention the JVM).

2024-07-18 03:36 UTC, ajay-gov approved these changes
Thanks @SirCipher, looks good to me.  I am ok to merge this change. @brohitbrose can you review when you get a chance as well.

2024-07-18 05:24 UTC, brohitbrose approved these changes

2024-07-19 14:49 UTC, horned-sphere approved these changes

2024-07-19 14:50 UTC, merged