Java server devguide missing code
swimos/swimos-docs pull request #241
Opened 2024-09-05 19:47 UTC by prestonmcgowan

A couple missing imports and a package statement made the QuickStart hard to follow.
I added the missing imports and package statement.

2024-09-06 08:37 UTC, PiggottDev requested changes
Thank you @prestonmcgowan for the PR.

Happy to front load the imports if that makes the guide easier to follow.

2024-09-06 08:37 UTC, PiggottDev commented on src/_java-server-devguide/2.3-hello-world.md
>  import swim.api.plane.AbstractPlane;
Please add `package tutorial;` statement in `MainPlane.java` block for consistency.

2024-09-18 17:25 UTC, prestonmcgowan commented
Added `package tutorial;` as requested :-)

2024-09-20 09:28 UTC, PiggottDev approved these changes

2024-09-20 09:29 UTC, merged