Issue 60/cli how to
swimos/swimos-docs pull request #64
Opened 2023-08-03 15:02 UTC by PiggottDev

Added a 'How to Stream Data Using the swim-cli' guide

@ajay-gov is it okay to use the fiveg endpoint as an example in the guide?

2023-08-03 16:48 UTC, ajay-gov requested changes
-  We should add details on `link `as well. Also we should explain `sync` and `link` first since that is the streaming part and  `get` afterwards. Could be useful to show sample messages for value and map lanes since the map lanes will have @update, @drop messages etc.

- Also can we document the `-f/-format` option to show json output?
- 
-  Maybe better to use one of the demos used in the swimOS doc site as reference, so maybe transit or cellular? 

One open question, should we have the introspection details here or should we have a separate how-to/reference material on introspection to document this?

2023-08-03 17:36 UTC, afolson requested changes

2023-08-03 17:36 UTC, afolson commented on src/_guides/cli.md
> +If a Swim application uses the `swim.meta.MetaKernel` then introspection endpoints are exposed.
Do we have anything more about the metakernel anywhere? That might be good to link here if so.

2023-08-03 17:36 UTC, afolson commented on src/_guides/cli.md
> +### Introspection
Per @ajay-gov 's comment in the PR, I like that introspection is mentioned here but I also think there should be another doc that covers it more in depth. I'll open an issue.

2023-08-03 18:09 UTC, ajay-gov commented on src/_guides/cli.md
> +### Introspection
I think we need a separate how-to for sure on introspection. We could reference the swim-cli in that one with the way to get the data from the meta lanes. Also `swim-cli` has a `reflect` command that helps with accessing the introspection API. All the more reason to have a separate how-to about intrrospection I think

2023-08-04 14:40 UTC, PiggottDev commented on src/_guides/cli.md
> +If a Swim application uses the `swim.meta.MetaKernel` then introspection endpoints are exposed.
I don't think we have anything on `metakernel` can include in the mentioned introspection guide.

2023-08-04 14:41 UTC, PiggottDev commented on src/_guides/cli.md
> +### Introspection
Removed introspection section as it's getting it's own guide.

2023-08-04 18:06 UTC, ajay-gov commented
Looks good. Couple of things
- We should say `warps` is for servers that are using secure websockets i.e. enabled with TLS and `warp` is for servers with non-secure websockets i.e TLS not enabled
- for `get` we should say that the cli terminates after getting the latest data from the lane unlike streaming where the cli continues to stream until the user breaks out with Ctrl-C

Otherwise looks great!!

2023-08-04 18:08 UTC, ajay-gov commented
One other comment, the color scheme on the Output Code blocks are tough for me to read. Eg, in this text
`{siteCount:1193,warnCount:115,alertCount:10}` 
the siteCount, warnCount and alertCount is not visible to me at all. 

Maybe it's just a problem for color blind folks. Is it okay for you all? @PiggottDev @afolson

2023-08-07 20:43 UTC, afolson commented
> One other comment, the color scheme on the Output Code blocks are tough for me to read. Eg, in this text `{siteCount:1193,warnCount:115,alertCount:10}` the siteCount, warnCount and alertCount is not visible to me at all.

@ajay-gov The syntax highlighter is trying to render this as JSON but it's not valid JSON since the keys aren't in double quotes. Removing `json` from the two ` ```json` code blocks fixes it.

2023-08-08 02:03 UTC, ajay-gov approved these changes
Looks goof to me!

2023-08-08 15:08 UTC, afolson approved these changes

2023-08-08 15:08 UTC, merged