Kafka Ingestion How To
swimos/swimos-docs pull request #67
Opened 2023-08-07 06:54 UTC by brohitbrose

Addresses #58.

2023-08-07 06:57 UTC, brohitbrose commented on src/_guides/kafka-ingestion.md
> +**Warning:** per the [`asyncStage()` reference](/FIXME), never run the infinite loop directly inside `didStart()` or another agent/lane callback function. Always delegate to `asyncStage()`.
Note the FIXME in the link destination here. The asyncStage() reference doesn't exist yet, but it absolutely should at some point.

2023-08-07 06:59 UTC, brohitbrose commented on _config.yml
>        - index.md
I have left out some necessary changes in this file, as well as in some of the `.html` files. I imagine #64 will be merged before this PR, and duplicating those changes would cause merge conflicts. Happy to add them anyway in if the reviewers prefer, though.

2023-08-08 02:22 UTC, ajay-gov commented on src/_guides/kafka-ingestion.md
> +**Warning:** per the [`asyncStage()` reference](/FIXME), never run the infinite loop directly inside `didStart()` or another agent/lane callback function. Always delegate to `asyncStage()`.
I think we can remove the warning about the `asyncStage` for now. Let's add the `asyncStage` reference guide soon to fix this.

2023-08-08 03:15 UTC, ajay-gov approved these changes
Looks good!

2023-08-08 20:48 UTC, ajay-gov requested changes
Can we change the name of the class containing the `KafkaConsumer` from `Main` tto say, `KafkaClient` or something similar to avoid confusion with the class that contains the `main` method .

All good otherwise

2023-08-08 22:55 UTC, ajay-gov approved these changes

2023-08-10 02:10 UTC, merged