Added agent-granularity guide
swimos/swimos-docs pull request #99
Opened 2023-09-20 15:52 UTC by PiggottDev

Closes #97

2023-09-20 17:16 UTC, StreamingDataApps requested changes
Looks good. Some minor changes are advisable.

2023-09-20 17:16 UTC, StreamingDataApps commented on src/_concepts/agent-granularity.md
this seems like overkill, so you should probably ignore...

"constructed (`/building/:buildingId/room/:roomId`)", since `buildingId` can occur with other `roomId`s, and vice versa.

2023-09-20 17:16 UTC, StreamingDataApps commented on src/_concepts/agent-granularity.md
"perform logic" is good and understandable. In object oriented design, the logic is described as behavior, it might be useful to mention behavior explicitly.

2023-09-20 17:16 UTC, StreamingDataApps commented on src/_concepts/agent-granularity.md
> +For example, lights in a room may be uniquely addressable however, if they are simply a boolean value of on or off, it may be worth rolling them up into a lane of the parent room node.
"worth" does seem to fit as used. "It may be cleaner to roll them up", or "it may be better to roll them up". "Worth" would work better if you were saying that it may not be worthwhile representing them as objects.

2023-09-20 17:16 UTC, StreamingDataApps commented on src/_concepts/agent-granularity.md
> +Addresses don't have enough behaviour or logic to need an agent of their own.
They don't have any behavior, to be exact. Going back to DDD, an "address" is a textbook example of a value object -- unchanging state with no need for supplemental identity.

2023-09-22 05:03 UTC, brohitbrose commented
I have nothing to add to this other than Fred's comments are excellent as always :)

2023-09-22 19:17 UTC, afolson approved these changes

2023-09-22 19:18 UTC, merged